services:
  - type: web
    name: masons-pl-dashboard
    runtime: python
    plan: free
    buildCommand: bash render-build.sh
    startCommand: bash start.sh
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: MANAGER_PASSWORD
        generateValue: true
      - key: VIEWER_PASSWORD
        generateValue: true
    autoDeploy: true
