services:
  - type: web
    name: masons-pl-dashboard
    runtime: python
    plan: free
    buildCommand: bash render-build.sh
    startCommand: panel serve dashboard.py --address 0.0.0.0 --port $PORT --allow-websocket-origin=* --num-procs=1
    envVars:
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: MANAGER_PASSWORD
        generateValue: true
      - key: VIEWER_PASSWORD
        generateValue: true
    autoDeploy: true
